export class AdvanceConstant {
  public static readonly ADV_API_VERSION_NAME: string = '3.1.0'
  public static readonly ADV_SDK_VERSION_NAME: string = '5.0.0'
  // SDK标识id
  public static readonly ADV_SDK_ID_MERCURY: string = '1'
  public static readonly ADV_SDK_ID_GDT: string = '2'
  public static readonly ADV_SDK_ID_CSJ: string = '3'
  public static readonly ADV_SDK_ID_BAIDU: string = '4'
  public static readonly ADV_SDK_ID_KS: string = '5'
  public static readonly ADV_SDK_ID_TANX: string = '7'

}